int i = 10;
int j = 2;
real w = 3.5;
print (i + i) * j * i;
print i + i * j * i;
print i + (i * j) * i;
print i + i * (j * i);
print (i + i) * j * i + "ualg" + 100;
print (i * i) / (j % i) * w;
print w - i * (i / j) % i + w;